### ISSUE TITLE
Meetings ?

### ISSUE THREAD

**Issue by GarethWGSMA** [camaraproject/CarrierBillingCheckOut#1]
Hi,

I cant find the meetings link. Do we have any meetings arranged ?

Thanks,
Gareth

**Comment by PedroDiez** [comment]
Hi Gareth, my intention is to schedule meetings from next week (weekly meetings in principle).

Initially i propose Thursday nex week to begin.
Also i would kindly ask in this forum for locations of people more interested in this WG in order to propose a time that can fit for all of us. So open to hear from everybody on this item.

Best Regards
Pedro

**Comment by GarethWGSMA** [comment]
No worries. I think I can accommodate almost any time - whatever works for the rest of the team.

Gareth

**Comment by alabajnaid** [comment]
Hi Pedro,

Looking forward for the meetings,
GMT+3 here, I suggest using a doodle tool to vote on possible slots.

**Comment by PedroDiez** [comment]
doodle: https://doodle.com/meeting/participate/id/bk87KRYd

**Comment by PedroDiez** [comment]
closing this issue as meetings are already scheduled
