### ISSUE TITLE
Update commonalities glossary with subproject relevant terms

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/CarrierBillingCheckOut#45]
https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by PedroDiez** [comment]
@shilpa-padgaonkar once we have internal aligment in the WG will go to commonalities for the terms to be included in the Glossary as a result of the contribution of this WG

---

Some initial compilation of terms for Carrier Billing WG:

**Carrier Billing (a.k.a. Direct Carrier Billing)**: An online payment process which allows users to make purchases by charging payments against OB Billing Systems, accordingly to the user's configuration in the OB.
**Purchase**: The action of acquiring a (set of) good(s)
**Payment**: The process of paying for that (set of) good(s)
**1-STEP Payment**: Payment process perfomed in one phase (i.e. one action), that involves all the OB Carrier Billing Systems checkings to guarantee the reservation of the involved amount and trigger the charging against Billing Systems.
**2-STEP Paymen**t: Payment process performed in two phases (i.e. two actions). First action deals with payment preparation with deals with the checkings to guarantee the reservation of the involved amount. Second action is an explict confirmation or cancellation of the payment by the user. Any payment not confirmed/cancelled by a given user is discarded after some time in order to avoid inconsistency in the billing systems. 

Please @bigludo7, @alabajnaid any improvement/refinement is more than welcome (as well as considering other terms if seen relevant)

**Comment by bigludo7** [comment]
Thanks !

_Few comments_:
Carrier Billing (a.k.a. Direct Carrier Billing): An online payment process which allows users to make purchases by charging payments against OB Billing Systems, accordingly to the user's configuration in the OB.  _In a common usage in the industry, the payment is processed on current account balance or charged on next bill generated for this line._

Purchase: The action of acquiring a (set of) good(s)/service(s) 
 Question for Pedro: Need to indicate if order fulfillment is triggered from this request. From Juan Carlos Garcia explanation I understood that fulfillment is not triggered. 

Payment: The process of paying for a (set of) good(s)/service(s)

1-STEP Payment: Payment process _performed_ in one phase (i.e. one action), that involves all the OB Carrier Billing Systems _checking_ _** (I will remove this) to guarantee the reservation of the involved amount**_ and trigger the charging against Billing Systems.

2-STEP Payment: Payment process performed in two phases (i.e. two actions). First action deals with payment preparation ** (I will remove this) with deals with the _checking_** to guarantee the reservation of the involved amount. Second action is an _explicit_ confirmation or cancellation of the payment by the user. Any payment not confirmed/cancelled by a given user is discarded after some time in order to avoid inconsistency in the billing systems.

**Comment by PedroDiez** [comment]
Agreed with the refinements (Carrier Billing, Payment, 1-STEP Payment, 2-STEP Payment)

Regarding Purchase, yes order fulfilment is not triggered by this request. Proposal:

Purchase: The action of acquiring a (set of) good(s)/service(s). _Order fulfilment_ is not triggered from this request as it relies on merchant's responsibility.

**Comment by PedroDiez** [comment]
If no further comments by Today, will generate PR towards Commonalities and closed this issue after merging

**Comment by PedroDiez** [comment]
@FahadTanwir-STC please take a look today/tomorrow. If no additional comments we go with these terms into Commonalities WG

**Comment by PedroDiez** [comment]
As no further comments, generating inout into Glossary Terms

**Comment by PedroDiez** [comment]
Contributed to https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by PedroDiez** [comment]
Set to closed as contribution already made to Commonalities
