### ISSUE TITLE
More descriptions for checkout and payment

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/CarrierBillingCheckOut#74]
Hi all, 

I think we need more descriptions on the two APIs. Currently, in readme and api yaml descriptions, like after i read through the documentations, i can not confidently says, that I understand the difference between this 2 APIs correctly. 

So i think, maybe we can have more descriptions to further clarify the difference between this two, either a diagram, or a two or three sentences user story.

**Comment by ShutingQing** [comment]
Can assign to me.

**Comment by bigludo7** [comment]
@ShutingQing We would like to move to only one API and exactly for the point you raised about confusion between these 2 APIs.
This discussion for one API is managed there: https://github.com/camaraproject/CarrierBillingCheckOut/issues/79

Then once we achieve this we can work on documentation. We'll have to because the plan is to integrate the documentation in the OAD definition itself.

**Comment by ShutingQing** [comment]
Okay. 

Actually i was initally think we can have more doc to help developers distinguish this two. But not like to suggest to combine them, cuz two api, as far as my understanding, has different scenarios, and usages are different. 

But if we do want to move to one api, it also also make sense as well. Cuz users may not want to spend time on selecting and learning the differences of the 2.

**Comment by PedroDiez** [comment]
Hi Miranda, 

Given taht we are going to move to a new proposal and the current two ones discarded i also suggest to deal with this in the common proposal.

We already have as a guidance this Issue: https://github.com/camaraproject/WorkingGroups/issues/164

So my suggestion is to work on this over the common proposal.

Then we can close this issue so far.

**Comment by ShutingQing** [comment]
Yes.
